name: check-installation-and-generate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

defaults:
  run:
    working-directory: example

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: example

      - uses: pnpm/action-setup@v2
        with:
          version: 8.10.5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: install dependencies
        run: |
          pnpm install
          pnpm add -D type-predicates-generator@latest

      - name: try generate
        run: |
          pnpm run codegen:openapi
          pnpm run codegen:tpg
