name: main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: check source codes (typecheck & eslint & prettier)
        run: |
          pnpm typecheck
          pnpm lint

      - name: Running Test
        run: pnpm test

      - name: Check successfully build
        run: |
          pnpm build
